name: Django CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations core
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test -v2 --keepdb

      - name: Archive project for deploy
        run: |
          mkdir -p release
          tar -czf release/django_app.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./release/django_app.tar.gz

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release
          path: ./artifact

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload artifact to server and deploy
        run: |
          scp ./artifact/django_app.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/django_app.tar.gz
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p ~/deploy/releases
            mv /tmp/django_app.tar.gz ~/deploy/releases
            cd ~/deploy/releases
            python manage.py runserver
          EOF